name: Docker Image CI

on:
  push:
    branches: [ "main" ] # 当代码推送到 main 分支时触发
  # pull_request:
  #   branches: [ "main" ] # 可选：当有 PR 合并到 main 分支时触发

jobs:
  build_and_push:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu Runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # 检出你的代码 (使用 v4)

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3 # 设置 Docker Buildx (使用 v3)

    - name: Log in to Docker Hub
      uses: docker/login-action@v3 # 登录 Docker Hub (使用 v3)
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }} # 使用 GitHub Secrets 中的用户名
        password: ${{ secrets.DOCKERHUB_TOKEN }} # 使用 GitHub Secrets 中的访问令牌

    - name: Build and push Docker image
      uses: docker/build-push-action@v5 # 构建并推送镜像 (使用 v5)
      with:
        context: . # Dockerfile 的上下文路径（当前目录）
        file: ./Dockerfile # Dockerfile 的路径
        push: true # 推送镜像到 Docker Hub
        tags: |
          chinazman/docker-proxy:latest
          chinazman/docker-proxy:${{ github.sha }}
        # 可选：添加缓存以加速构建
        # cache-from: type=gha
        # cache-to: type=gha,mode=max